title: tokyo-night-theme
description: "Tokyo night theme"
encoding: utf-8
enable_dark_theme: true
exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]
footer: "Made in 2025"
plugins:
  - jekyll-last-modified-at